dist: xenial
language: node_js
node_js:
  - lts/*
cache: npm
before_install:
  - npm i -g npm
  - npm i -g typescript tslint @angular/cli angular-cli-ghpages ng-git-gen ng-md-components
  - curl -L https://github.com/mmarkdown/mmark/releases/download/v2.0.46/mmark_2.0.46_linux_amd64.tgz -o mmark.tgz
  - tar xf mmark.tgz
  - sudo ln -s "$PWD/mmark" /usr/local/bin/mmark
  - sudo -H pip3 install xml2rfc
  - sudo -H pip3 install -U six
addons:
  apt:
    packages:
      - python3-lxml
      - python3-pip
      - python3-html5lib
      - html-xml-utils
      - tree
jobs:
  include:
    - stage: deploy
      script:
        - cd "$TRAVIS_BUILD_DIR"
        - ng-git-gen -p "$PWD" -g 'https://github.com/Fantom-foundation/fantom-rfcs' -l -b 'make html_body' -e '.html' -i "import { NgxPageScrollModule } from 'ngx-page-scroll';" -f '.replace(/href="#/g, `pageScroll href="#`)' -r rfc -s './xml2rfc.css' -vv
        - ng-git-gen -p "$PWD" -g 'https://github.com/Fantom-foundation/go-lachesis.wiki.git' -l -o '.md' -vv
        - ng-md-components -d "$PWD"
        - cp /usr/local/lib/python3.*/dist-packages/xml2rfc/data/{xml2rfc.js,xml2rfc.css} src/app/rfc/generated/
        - ng build --prod
        - tree -a
        - cp *.md dist/fantom-dev && ngh --dir='dist/fantom-dev' --repo=https://GH_TOKEN@github.com/Fantom-foundation/Fantom-foundation.github.io --name="$(git log -1 --pretty=format:'%an')" --branch='master' --message="$TRAVIS_COMMIT_MESSAGE"
branches:
  only:
    - master
env:
  global:
    secure: 'c5DcsPmApDGIWbKXWxJDAWgx9B6YtT8vZsjQxUo8jl1cnNMdBuVjnD7uxALq2e/et+xGaW4zHMU4JajdUVzjLyfLh/s2I+AcPzGSjhdnuQWY6TmuRlK9vIrwfNX/tgcAVk0aUmLYoiY834U2PVE4noE6OTH1ARYh2Ttm8Ypg7ca4QmSg6hSHrvM3IhE7Ua95hjWcEaND62QWJf6BnjJ9t1fcwTScxz8uS/A2CxDwu3rDKmXYjHswxZ2eN7p9A5SZ5yK7YVeGmJAke7LTpHFpOtK0VLw2RS6Obbg2tk7S4t5DkXclkWLin99ypwPnUR2KlZmhKRXE2X65mL30GA2Z52ZrCjqmDMEXauz1MxX8Sk6A6vs/KA9b/SjawyNUCKV10llmdbENSYUyZWEZm+ZPf06palMbljQlSItiXIhBWj/bVSpAV26In3TfT6ks4wzgGvHYPpYvPvaodTvErQIwyhnXFEQCIyAKvrmmXWFafkO3r7bpJaQnJihAKC78yxwAHF/2NW5pABwd04onc/+U4cgc6jPRcasshhsFghHLk6bpvkfH3H3L+Uuvp6DtgYEoExCByJnnd4yWtlenUCpvCQNxpD4NYEEJxjwqJ9rFR2BqmGQ9Xj1iwWb55Wk9AaFaZsHgolcSTm1UgqNqK92wFRxCQVB8BAxcTRqX+KPzq/w='
